from django.urls import path, include
from .views import (
    CatalogView,
    CategoryListView,
    PopularProductsView,
    SalesView,
    BannersView,
    BasketView,
    BasketDeleteView,
    SignInView,
    SignUpView,
    SignOutView,
    OrderCreateView,
    OrderDetailView,
    PaymentView,
    ProfileView,
    ChangePasswordView,
    AvatarUpdateView,
    TagListView,
    ProductDetailView,
    CreateReviewView,
    LimitedProductsView,
)

urlpatterns = [
    path('sign-in/', SignInView.as_view(), name='sign-in'),
    path('sign-up/', SignUpView.as_view(), name='sign-up'),
    path('sign-out/', SignOutView.as_view(), name='sign-out'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('catalog/', CatalogView.as_view(), name='catalog'),
    path('sales/', SalesView.as_view(), name='sales'),
    path('banners/', BannersView.as_view(), name='banners'),
    path('basket/', BasketView.as_view(), name='basket'),
    path('orders/', OrderCreateView.as_view(), name='order-create'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('tags/', TagListView.as_view(), name='tags-list'),
    path('profile/password/', ChangePasswordView.as_view(), name='change-password'),
    path('profile/avatar/', AvatarUpdateView.as_view(), name='avatar-update'),
    path('products/popular/', PopularProductsView.as_view(), name='popular-products'),
    path('products/limited/', LimitedProductsView.as_view(), name='limited-products'),
    path('payment/<int:id>/', PaymentView.as_view(), name='payment'),
    path('cart/<int:id>/', BasketDeleteView.as_view(), name='cart-item-delete'),
    path('order/<int:id>/', OrderDetailView.as_view(), name='order-detail'),
    path('product/<int:id>/', ProductDetailView.as_view(), name='product-detail'),
    path('product/<int:id>/reviews/', CreateReviewView.as_view(), name='product-review'),
]